version: "3.8"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.production
    working_dir: /app
    image: mdshishov/devops-for-developers-project-74:latest
    command: ["make", "test"]
